Model:
    name: "InSPyReNet_SwinB"
    depth: 64
    pretrained: True
    base_size: [1024, 1024]
    threshold: NULL

Train:
    Dataset:
        type: "RGB_Dataset"
        root: "/home/rafael/datasets/DSCollections_1024x1024/"
        # sets: ['shorttest']
        sets: [
        'aim500', 'clothing', 'dis5k', 'ecommerce', 'foodseg103', 'hrsod', 'p3m10k', 'segfood', 'ukcarsdataset1005', 'voc2012',
        'am2k', 'cocostuff_fg', 'dut-omron', 'ecssd', 'fss-1000', 'imaterialistfurniturefgvc5', 'pascal-s', 'shopee', 'vehicleclassificationdataset',
        'animalsimagedataset', 'duts', 'fashiondataset', 'hku-is', 'msra10k', 'pixelcut_20221031', 'uhrsd', 'vehicleimagesdataset'
        ]
        transforms:
            #static_resize: 
            #    size: [1024, 1024]
            #random_scale_crop:
            #    range: [0.75, 1.25]
            random_flip:
                lr: True
                ud: False
            #random_rotate:
            #    range: [-10, 10]
            #random_image_enhance:
            #    methods: ['contrast', 'sharpness', 'brightness']
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 4
        shuffle: True
        num_workers: 12
        pin_memory: True
    Optimizer:
        type: "Adam"
        lr: 1.0e-05
        weight_decay: 0.0
        mixed_precision: False
    Scheduler:
        type: "PolyLr"
        epoch: 6000000
        gamma: 0.9
        minimum_lr: 1.0e-07
        warmup_iteration: 1000
    Checkpoint:
        checkpoint_epoch: 1
        checkpoint_dir: "snapshots/Plus_Ultra2"
    Debug:
        keys: ['saliency', 'laplacian']
    
Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/Test_Dataset"
        sets:  ['DUTS-TE', 'DUT-OMRON', 'ECSSD', 'HKU-IS', 'PASCAL-S', 'DAVIS-S', 'HRSOD-TE', 'UHRSD-TE']
        transforms:
            # static_resize: 
            #     size: [1024, 1024]
            dynamic_resize:
                L: 1280
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/Plus_Ultra2"

Eval:
    # gt_root: "data/Test_Dataset"
    gt_root: 'data/'
    pred_root: "results"
    result_path: "results/"
    datasets: ['evalset']
    # datasets: ['shorttest']
    metrics: ['Sm', 'mae', 'adpEm', 'maxEm', 'avgEm', 'adpFm', 'maxFm', 'avgFm', 'wFm', 'mBA']
